In [8]:
import numpy as np

In [16]:
import numpy as np
t1="hello"
ar1=np.array(t1)
ar1.dtype

dtype('<U5')

In [17]:
arr=(1,2,3,4,5)
list(arr)

[1, 2, 3, 4, 5]

In [18]:
type(list(arr))

list

In [19]:
import numpy as np
t1={"a":100, "b":200}
ar1=np.array(t1)
ar1

array({'a': 100, 'b': 200}, dtype=object)

In [20]:
arr*2

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5)

In [21]:
pip list


Package                   Version
------------------------- ---------------
anyio                     4.2.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.14.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
colorama                  0.4.6
comm                      0.2.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.19.1
fqdn                      1.5.1
idna                      3.6
ipykernel                 6.29.2
ipython                   8.21.0
Note: you may need to restart the kernel to use updated packages.
ipywidgets                8.1.2
isoduration               20.11.0
jedi          

In [22]:
ar2=[1,2,3.45,9,89,2]
np_ar=np.array(ar2)
np_ar

array([ 1.  ,  2.  ,  3.45,  9.  , 89.  ,  2.  ])

In [23]:
new_ar=np.append(np_ar,[56,90,89])          #To add multiple values to array
new_ar

array([ 1.  ,  2.  ,  3.45,  9.  , 89.  ,  2.  , 56.  , 90.  , 89.  ])

In [24]:
#insert
#based on index value to add the element  into array
#np.insert(array_to_be_modified,index_position,value)
new_ar=np.insert(np_ar,2,123)
new_ar

array([  1.  ,   2.  , 123.  ,   3.45,   9.  ,  89.  ,   2.  ])

In [25]:
#to insert multiple values in array
#np.insert (array_to_be_modified,index_position,values in list or tuple)
new_ar=np.insert(np_ar,2,(456,932,189))
new_ar

array([  1.  ,   2.  , 456.  , 932.  , 189.  ,   3.45,   9.  ,  89.  ,
         2.  ])

In [26]:
nr=np.delete(np_ar,np.where(np_ar==2.0))        #delete num 2 from the array
nr

array([ 1.  ,  3.45,  9.  , 89.  ])

In [27]:
nr=np.delete(np_ar,np.where(np_ar==1.0))         #delete num 1 in array
nr

array([ 2.  ,  3.45,  9.  , 89.  ,  2.  ])

In [28]:
#to delete number of values in array
nr=np.setdiff1d(np_ar,[1.0,2.0,9.0])
nr

array([ 3.45, 89.  ])

In [29]:
#to delete based on index position
nr=np.delete(np_ar,3)
nr

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  ])

In [30]:
#to delete multiple values based on index position
nr=np.delete(np_ar,[1,2])
nr

array([ 1.,  9., 89.,  2.])

In [33]:
#
l1=[1,45,23,90,78,12,94,26,15,8,7]
new_ar=np.array(l1)

In [34]:
#filter in numpy array
new_ar<30      #returns true if the num is less than 30 otherwise returns false

array([ True, False,  True, False, False,  True, False,  True,  True,
        True,  True])

In [35]:
new_ar[new_ar>30]

array([45, 90, 78, 94])

In [36]:
new_ar[new_ar<30]

array([ 1, 23, 12, 26, 15,  8,  7])

In [37]:
#print the values < 20 and > 50
# -->for and operation using &
# -->for or operation use
(new_ar<20)&(new_ar>50)

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [38]:
new_ar[(new_ar>20) & (new_ar<50)]

array([45, 23, 26])

In [39]:
#to replace value in array
new_ar==23                      #23 place displays TRUE remaining shows FALSE

array([False, False,  True, False, False, False, False, False, False,
       False, False])

In [41]:
new_ar[new_ar==23]=156         # 23 replace with 156

In [43]:
new_ar

array([  1,  45, 156,  90,  78,  12,  94,  26,  15,   8,   7])

In [44]:
#to create array full of zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
#To create 2D array full of zeros
#Syntax  -->np.zeros([num_of_rows,num_of_cols])
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# Type convert the element in array
# To find the numpy datatype of element present in array -->dtype
#type(ar)
np_ar.dtype

dtype('float64')

In [51]:
# We can convert the values in numpy array to various bits
# They are
#int8,int16,int32,int64
#float16,float32,float64
#complex64,complex128
#unit32,unit16
ar=np.zeros([2,4], dtype='int16')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [52]:
ar=np.zeros([2,4], dtype='float16')
ar


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [53]:
ar=np.zeros([2,4], dtype='complex64')
ar


array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [ ]:
#TASKS:

In [54]:
#TASK  1.How to create range of element as array
import numpy as np
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# TASK 2.How to convert a 1D array to multidimensional array
ar1
len(ar1)

10

In [56]:
reshaped_array=ar1.reshape(10,1)

In [57]:
reshaped_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [58]:
#TASK 3.How to create array of identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
#TASK 4.How to perform slicing in multidimensional array
ar2=np.arange(25).reshape(5,5)

## 

In [61]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
# TASK 5.How to find the mean,median,sum,varience,standard deviation of an array
#MEAN
import numpy as np
ar3=[1,2,3,4,5]
x=np.mean(ar3)
print(x)

3.0


In [63]:
#MEDIAN
x=np.median(ar3)
print(x)

3.0


In [1]:
#MODE
from scipy import stats as st
ar4=[15,25,35,15,20,30]
x=st.mode(ar4)
print(x)

ModeResult(mode=15, count=2)


In [4]:
#Varience
import numpy as np
print(np.var(ar4))

55.555555555555564


In [5]:
#Standard Deviation
print(np.std(ar4))

7.4535599249993
