In [2]:
import numpy as np
ar1=np.arange(30)


In [3]:
ar1
len(ar1)

30

In [5]:
reshaped_array=ar1.reshape(30,1)

In [6]:
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [12]:
#identity matrix can be created using 2 function 
#eye() --> used to define rows and coloumns
#identity()--> used to define same no of rows and coloumns
#syntax-->np.identity(5)
#syntax -->np.eye(5)
np.eye(5)

In [8]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:

np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [17]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
#To perform multidimensionalslicing
ar2=np.arange(25).reshape(5,5)

In [32]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#ar2[rows,coloumns,step]
#ar2[row_start :now_end,col_start,col_end,step]
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [21]:
ar2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
ar2[1 :3,1:3]

array([[ 6,  7],
       [11, 12]])

In [34]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [35]:
ar3=np.arange(50).reshape(5,10)
#tasks
#1.)to print 27,28,37,,38,--->
#2.)Print 34,35,44,45
#3.) Print 18,19
#4.)Print 31,31,40,41

In [39]:
#linspace()
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
np.sum(ar3)

1225

In [41]:
#To add based on coloumn wise axis=0
np.sum(ar3,axis=0) # here axis is in-built function


array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [43]:
# To add based on row wise axis=1
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [45]:
#IMP POINTS
#1.mean --->average
#2.meadian--->center value
#3.mode ---> max num of repeated elements
#4.variance ---> meadian/toatal num of elements
#5.std deviation --->sqrt of variance



In [46]:
#linspace()
#DEFINATION : It is used to print the evenly seperated pointed between 2 range of values
#-->linspace(start,end)
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [48]:
#---> linspace9start,end,num of values)
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [49]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [51]:
# random module
#np.random.randint(start,end)
#To generate random numbers btween the range
#np.random.randint(40)
# OR
np.random.randint(20,30)

20

In [53]:

np.random.randint(30)

12

In [56]:
np.random.randint(20,30,3) #np.random.randint(start,end,numof values we want)

array([28, 25, 21])

In [57]:
#rand() ---->
# To get the randomly generated from 0 t0 1,based on Uniform distribution
np.random.rand(4)

array([0.11263212, 0.06564924, 0.88370747, 0.73466643])

In [58]:
np.random.rand(7)

array([0.65996337, 0.59296264, 0.48081156, 0.71308929, 0.0712408 ,
       0.33761391, 0.01123771])

In [59]:
np.random.rand(3,4)  #(3 rows,4 columns)

array([[0.32046938, 0.04256049, 0.74093648, 0.17172613],
       [0.22175685, 0.80099486, 0.92687278, 0.32485233],
       [0.47609008, 0.99458745, 0.58060946, 0.07228435]])

In [60]:
#rand()----->
# To get the randomly generated from 0 t0 1,based on Normalized distribution

np.random.randn(5)

array([ 1.9509859 , -0.93478099,  0.81873608,  0.230556  , -1.14020109])

In [61]:
np.random.randn(5,4)

array([[ 0.99275966, -0.13746307,  0.02867556, -0.18769086],
       [ 0.85547883,  2.11177203,  0.53806882,  0.03097438],
       [ 0.66461736, -0.1965324 ,  0.6309606 ,  1.84827197],
       [ 1.23024033,  1.29876508,  0.56216065,  0.42259453],
       [ 0.56105256, -0.98166523,  0.97550673, -1.55164223]])

In [62]:
ar3.max()

49

In [63]:
ar3.min()

0

In [67]:
#To find the index of min values
l=[56,89,90,67,45]
print(l.index(45))
print(l.index(90))

4
2


In [68]:
print(ar3.tolist()) 

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [72]:
# armin() and argmax() are used to find min and max of an array by converting list into an array
l=[56,89,90,67,45]
np1=np.array(l)
print(np1.argmin())   # argmin() ---> Used to find min value of index  in an array
print(np1.argmax())   # argmax() ---> Used to find max value of index in an array

4
2


In [73]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [74]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [89]:
fname=np.array(["sita","lali"],dtype=str)
lname=np.array(['t',"ln1","ln2"],dtype=str)


In [ ]:
#pandas
#pandas is built on numpy,numpy is required for operating pandas
import pandas as pd

In [6]:
import numpy as np
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [9]:
ser1=pd.Series([1,2,3,4,5],['australia','india','newzealand','usa','uk'])

In [10]:
ser1

australia     1
india         2
newzealand    3
usa           4
uk            5
dtype: int64

In [11]:
ser1['india']

2

In [4]:

ser1=pd.Series([1,2,3,4,5],['australia','india','newzealand','usa','uk'])

In [6]:
ser1[1:3]

india         2
newzealand    3
dtype: int64

In [8]:
import numpy as np
df=pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'])

In [9]:
df

0         1         2         3
a -0.755815  0.054605 -1.445321 -0.015912
b -0.680714 -0.123603  0.348570 -0.865926
c  0.088328 -0.016228  1.778424 -0.039553
d  0.343176  0.636433  0.847087 -1.059862
e -0.365278 -1.198730 -0.456698 -0.064870

In [10]:
d={'col':[1,2],'co12':[3,4],'co13':[5,6]}
d

{'col': [1, 2], 'co12': [3, 4], 'co13': [5, 6]}

In [11]:
df=pd.DataFrame(data=d)
df

col  co12  co13
0    1     3     5
1    2     4     6

In [12]:
df=pd.DataFrame(d,['row1','row2'])

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col     2 non-null      int64
 1   co12    2 non-null      int64
 2   co13    2 non-null      int64
dtypes: int64(3)
memory usage: 64.0+ bytes


In [15]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [16]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col', 'co12', 'co13'], dtype='object')]

In [17]:
df.size

6

In [23]:
df=pd.DataFrame(data=d)
df

col  co12  co13
0    1     3     5
1    2     4     6

In [25]:
df.dtypes

col     int64
co12    int64
co13    int64
dtype: object

In [35]:
df.T

0  1
col   1  2
co12  3  4
co13  5  6

In [28]:
df.columns

Index(['col', 'co12', 'co13'], dtype='object')

In [34]:
np.random.randn(5, 4), ['A','B','C','D','E'],['W','X','Y','Z']

(array([[ 1.32322062,  1.70441183, -1.46486266, -0.34105014],
        [ 1.22774951, -2.11649552,  0.03972749, -1.54976152],
        [ 1.02482663, -1.05898313,  0.42940314, -0.07153094],
        [-1.88100751, -0.15428558, -0.34407224,  2.60635229],
        [-0.48440798,  2.16382876,  0.70725987, -0.20553693]]),
 ['A', 'B', 'C', 'D', 'E'],
 ['W', 'X', 'Y', 'Z'])

In [29]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [30]:
df.ndim

2

In [33]:
df['col']

0    1
1    2
Name: col, dtype: int64

In [36]:
#TASKS:

In [38]:
#TASK 1.) Add anothjer row to this arrayrow to be added = [12,23,45] ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]]

import numpy as np
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
row_to_be_added = np.array([12, 23, 45])
result = np.vstack((ini_array, row_to_be_added))
print("Result:")
print(result)


Result:
[[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [12 23 45]]


In [39]:
#TASK 2.)Find the frequency of all element in the series se = pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])

import pandas as pd
se = pd.Series([1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5])
frequency = se.value_counts()
print("Frequency of elements in the series:")
print(frequency)


Frequency of elements in the series:
2    4
1    3
3    3
4    2
5    1
Name: count, dtype: int64


In [40]:
#TASK 3.)Reshape the series ser into a dataframe ser = pd.Series(np.random.randint(1, 10, 35))

import pandas as pd
import numpy as np
ser = pd.Series(np.random.randint(1, 10, 35))
# Reshape the series into a DataFrame with 7 rows and 5 columns
df = pd.DataFrame(ser.values.reshape(7, 5))
print(df)


   0  1  2  3  4
0  7  2  3  8  2
1  7  5  1  7  3
2  6  6  1  2  4
3  4  8  6  8  5
4  3  3  5  4  6
5  5  4  4  2  2
6  8  2  7  6  4


In [41]:
#TASK 4.)Find the positions of numbers that are multiples of 3 from ser  ser = pd.Series(np.random.randint(1, 10, 10))import pandas as pd

import numpy as np
ser = pd.Series(np.random.randint(1, 10, 10))
# Find positions of numbers that are multiples of 3
positions = ser.index[ser % 3 == 0]
print("Positions of numbers that are multiples of 3:")
print(positions)


Positions of numbers that are multiples of 3:
Index([1, 2, 8], dtype='int64')
